/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CollegueRouteImport } from './routes/collegue'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegueRoute = CollegueRouteImport.update({
  id: '/collegue',
  path: '/collegue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collegue': typeof CollegueRoute
  '/index.html': typeof IndexDothtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collegue': typeof CollegueRoute
  '/index.html': typeof IndexDothtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collegue': typeof CollegueRoute
  '/index.html': typeof IndexDothtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/collegue' | '/index.html'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/collegue' | '/index.html'
  id: '__root__' | '/' | '/$' | '/collegue' | '/index.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CollegueRoute: typeof CollegueRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collegue': {
      id: '/collegue'
      path: '/collegue'
      fullPath: '/collegue'
      preLoaderRoute: typeof CollegueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CollegueRoute: CollegueRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
